# Generated by Django 4.0.3 on 2022-04-04 09:15

import blog_new.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_new', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=blog_new.models.upload_to, verbose_name='Image'),
        ),
    ]
