# Generated by Django 4.0.3 on 2022-04-06 11:44

import blog_new.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_new', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=blog_new.models.upload_to, verbose_name='image'),
        ),
    ]
